//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariam_0522068
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_
    {
        public int admin_id { get; set; }
        public string admin_username { get; set; }
        public string admin_pass { get; set; }
    }
}
