//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariam_0522068
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int userid { get; set; }
        public string Username { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Phonenumber { get; set; }
        public string City { get; set; }
    }
}
